changelog:
  exclude:
    labels:
      - "release"
      - "dependencies"
  categories:
    - title: ⚠️ BREAKING CHANGES
      labels:
        - "breaking change"
    - title: 🏚️ Deprecated Items
      labels:
        - deprecated
    - title: 🎉 New Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📓 Documentation Updates
      labels:
        - documentation
    - title: ☑️ TypeScript Changes
      labels:
        - typescript
    - title: Other Changes
      labels:
        - "*"
