name: Push Jobs
on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
  test:
    name: Test Pushed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Build Package
        run: pnpm build
      - name: Run ESLint
        run: pnpm lint:ci
