name: Release New Version
on:
  release:
    types: [published]
jobs:
  test:
    name: "Publish Release"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Build Library
        run: pnpm build
      - name: Lint Code
        run: pnpm lint:ci
      - name: Publish Library
        run: pnpm publish --access=public --no-git-checks
        env:
          NPM_CONFIG_PROVENANCE: true
